:stem:

= Représentation des Nombres de Fibonacci

== Notation récursive des nombres de Fibonacci

Notons stem:[AA n in NN], `fib(n)` le nombre de Fibonacci à l'index `n`, posant la définition :

====
stem:[{
( fib(0) = 0 ),
( fib(1) = 1 ),
({: AA n >= 2, fib(n) = fib(n-1) + fib(n-2) :})
:}]
====

== Notation Matricielle

Notons pour une génération n

- stem:[a_n] le nombre de lapins _adultes_
- stem:[b_n] le nombre de lapins _bébés_

Alors une génération au rang n vérifie le système

stem:[{ (a_{n+1} = a_n + b_n),(b_{n+1} = a_n)
:}]

Ce qui correspond à la notation matricielle

stem:[( (a_{n+1}),(b_{n+1})) = ((1,1),(1,0)) ((a_n),(b_n) )]

====
On fait apparaitre la matrice stem:[Q = (
(1,1),
(1,0)
)], nommée d'après sa forme.
====

En raisonnant de proche en proche, on peut montrer que

stem:[Q^n=(
(fib(n+1), fib(n)),
(fib(n), fib(n-1))
)]

CAUTION: Il y a un décalage d'indice entre le rang n+1 de Fibonacci et la puissance n de Q.

Donc

====
stem:[AA n, fib(n) = {:Q^{n-1}:}_{0,0}]
====

[TIP]
====
On notera que stem:[det(Q) = -1 != 0], donc Q admet une matrice inverse stem:[Q^{-1}=((0,1), (1,-1))]

Ainsi, par exemple, stem:[{
(fib(0) = {:Q^{-1}:}_{0,0} = 0),
(fib(1) = {:Q^0:}_{0,0} = Id_{0,0} = 0)
:}]
====


