= Fibonacci Extrême
:author:        Edwyn Tech
:owner:         Edwyntech
:email:         mailto:contact@edwyn.tech
:project:       fibonacci
:repo:          https://github.com/{owner}/{project}
:ci:            {repo}/actions/workflows/ci.yaml
:linkedin:      https://www.linkedin.com/company/74937487/
:youtube:       https://www.youtube.com/@{owner}
:twitch:        https://www.twitch.tv/{owner}
:badges:        https://img.shields.io/badge

image:{ci}/badge.svg[link={ci},window=_blank]

Un exercice technique que nous utilisions, basé sur le calcul de la suite de Fibonacci.

== Énoncé

Nous souhaitons calculer les valeurs de la suite de Fibonacci qui se définit comme suit :

- fibonacci(0) = 0
- fibonacci(1) = 1
- n >= 2, fibonacci(n) = fibonacci(n-1) + fibonacci(n-2)

TIP: Les deux notations utilisées dans l'exercice sont explicitées link:NOTATION.adoc[ici]

L'exercice se fait pour un client qui souhaite calculer les nombres de Fibonacci pour des indices jusqu'à 1 000 000.

== Structure

Ce projet est construit comme un projet NodeJS.

Il se base sur le template link:https://github.com/RomainFallet/typescript-example[typescript-example] de link:https://github.com/RomainFallet[Romain Fallet].

== Cycle De Vie

|===

|Construction|`npm build`
|Test|`npm test`

|===

== Auteur

image::https://img.shields.io/badge/Par_email-email?style=social&logo=microsoftoutlook&label={author}[link={email}]
image::{badges}/Sur_LinkedIn-email?style=social&logo=linkedin&label={author}[link={linkedin},window=_blank]
image::https://img.shields.io/badge/Youtube-channel?style=social&logo=youtube&label={author}[link={youtube},window=_blank]
image::https://img.shields.io/badge/Twitch-channel?style=social&logo=twitch&label={author}[link={twitch},window=_blank]
