= Fibonacci Extrême
:author:        Edwyn Tech
:owner:         Edwyntech
:email:         mailto:contact@edwyn.tech
:project:       fibonacci
:repo:          https://github.com/{owner}/{project}
:ci:            {repo}/actions/workflows/ci.yaml
:linkedin:      https://www.linkedin.com/company/74937487/
:youtube:       https://www.youtube.com/@EdwynTech
:twitch:        https://www.twitch.tv/edwyntech
:badges:        https://img.shields.io/badge

image:{ci}/badge.svg[link={ci},window=_blank]

Un exercice technique que nous utilisions, basé sur le calcul de la suite de Fibonacci.

Voici l'énoncé:

[quote]
====
Nous souhaitons calculer les valeurs de la suite de Fibonacci qui se définit comme suit :
[stem,latexmath]
++++
{
fibonacci(0)=0 \\
fibonacci(1)=1 \\
\forall n \in N, n \geq 2 \Rightarrow fibonacci(n)=fibonacci(n-1)+fibonacci(n-2)
}
++++
====

À partir de l'indice 100, on s'amuse...

Notons

- stem:[a_n] la suite des lapins adultes
- stem:[b_n] la suite des lapins bébés

Alors les deux suites se définissent par:

[stem,latexmath]
++++
\left\{
\begin{array}{ll}
a_0=0,\\
b_0=1,\\
a_{n+1} = a_{n} + b_{n},\\
b_{n+1} = a_{n}.
\end{array}
\right.
++++

Introduisant la matrice

[stem,latexmath]
++++
Q=\begin{pmatrix}
1 & 1\\
1 & 0
\end{pmatrix}
++++

Dans l'équation

[stem,latexmath]
++++
\begin{pmatrix}a_{n+1}\\b_{n+1}\end{pmatrix}=Q\begin{pmatrix}a_n\\b_n\end{pmatrix}
++++

Pour retrouver que

[stem,latexmath]
++++
\forall n \in N, n \geq 2 \Rightarrow fibonacci(n)=Q^{n-1}_{00}
++++

== Structure

Ce projet est construit comme un projet NodeJS.

Il se base sur le template link:https://github.com/RomainFallet/typescript-example[typescript-example] de Romain Fallet.

== Cycle De Vie

|===

|Construction|`npm build`
|Test|`npm test`

|===

== Auteur

image::https://img.shields.io/badge/Par_email-email?style=social&logo=microsoftoutlook&label={author}[link={email}]
image::{badges}/Sur_LinkedIn-email?style=social&logo=linkedin&label={author}[link={linkedin},window=_blank]
image::https://img.shields.io/badge/Youtube-channel?style=social&logo=youtube&label={author}[link={youtube},window=_blank]
image::https://img.shields.io/badge/Twitch-channel?style=social&logo=twitch&label={author}[link={twitch},window=_blank]
